import { CountriesStrings as t } from '@core/dictionaries';
import { SelectOption } from '@shared/ui';

export const ContentCountryFilterParams = {
  placeholder: 'Select countries',
  options: [
    { id: 'filter-country-0', label: t.USA, value: 'США' },
    { id: 'filter-country-1', label: t.Russia, value: 'Россия' },
    { id: 'filter-country-2', label: t.France, value: 'Франция' },
    { id: 'filter-country-3', label: t.Germany, value: 'Германия' },
    { id: 'filter-country-4', label: t.Foreign, value: 'Зарубежные' },
    { id: 'filter-country-5', label: t.China, value: 'Китай' },
    { id: 'filter-country-6', label: t.Japan, value: 'Япония' },
    { id: 'filter-country-7', label: t.Italy, value: 'Италия' },
    { id: 'filter-country-8', label: t.Spain, value: 'Испания' },
    { id: 'filter-country-9', label: t.Ukraine, value: 'Украина' },
    { id: 'filter-country-10', label: t.NewZealand, value: 'Новая Зеландия' },
    { id: 'filter-country-11', label: t.Denmark, value: 'Дания' },
    { id: 'filter-country-12', label: t.Indonesia, value: 'Индонезия' },
    { id: 'filter-country-13', label: t.Colombia, value: 'Колумбия' },
    { id: 'filter-country-14', label: t.Mexico, value: 'Мексика' },
    { id: 'filter-country-15', label: t.Switzerland, value: 'Швейцария' },
    { id: 'filter-country-16', label: t.Sweden, value: 'Швеция' },
    { id: 'filter-country-17', label: t.SouthAfrica, value: 'Южная Африка' },
    { id: 'filter-country-18', label: t.Austria, value: 'Австрия' },
    { id: 'filter-country-19', label: t.Korea, value: 'Республика Корея' },
    { id: 'filter-country-20', label: t.Bulgaria, value: 'Болгария' },
    { id: 'filter-country-21', label: t.Norway, value: 'Норвегия' },
    { id: 'filter-country-22', label: t.Monaco, value: 'Монако' },
    { id: 'filter-country-23', label: t.Australia, value: 'Австралия' },
    { id: 'filter-country-24', label: t.Ireland, value: 'Ирландия' },
    { id: 'filter-country-25', label: t.Netherlands, value: 'Нидерланды' },
    { id: 'filter-country-26', label: t.Canada, value: 'Канада' },
    { id: 'filter-country-27', label: t.Czech, value: 'Чехия' },
    { id: 'filter-country-28', label: t.HongKong, value: 'Гонконг' },
    { id: 'filter-country-29', label: t.UK, value: 'Великобритания' },
    { id: 'filter-country-30', label: t.Chile, value: 'Чили' },
  ] satisfies SelectOption[],
};
