import { SelectOption } from '@shared/ui';

export const ContentCountryFilterParams = {
  placeholder: 'Select countries',
  options: [
    { id: 'filter-country-0', label: 'USA', value: 'США' },
    { id: 'filter-country-1', label: 'Russia', value: 'Россия' },
    { id: 'filter-country-2', label: 'France', value: 'Франция' },
    { id: 'filter-country-3', label: 'Germany', value: 'Германия' },
    { id: 'filter-country-4', label: 'Foreign', value: 'Зарубежные' },
    { id: 'filter-country-5', label: 'China', value: 'Китай' },
    { id: 'filter-country-6', label: 'Japan', value: 'Япония' },
    { id: 'filter-country-7', label: 'Italy', value: 'Италия' },
    { id: 'filter-country-8', label: 'Spain', value: 'Испания' },
    { id: 'filter-country-9', label: 'Ukraine', value: 'Украина' },
    { id: 'filter-country-10', label: 'New Zealand', value: 'Новая Зеландия' },
    { id: 'filter-country-11', label: 'Denmark', value: 'Дания' },
    { id: 'filter-country-12', label: 'Indonesia', value: 'Индонезия' },
    { id: 'filter-country-13', label: 'Colombia', value: 'Колумбия' },
    { id: 'filter-country-14', label: 'Mexico', value: 'Мексика' },
    { id: 'filter-country-15', label: 'Switzerland', value: 'Швейцария' },
    { id: 'filter-country-16', label: 'Sweden', value: 'Швеция' },
    { id: 'filter-country-17', label: 'South Africa', value: 'Южная Африка' },
    { id: 'filter-country-18', label: 'Austria', value: 'Австрия' },
    { id: 'filter-country-19', label: 'Republic of Korea', value: 'Республика Корея' },
    { id: 'filter-country-20', label: 'Bulgaria', value: 'Болгария' },
    { id: 'filter-country-21', label: 'Norway', value: 'Норвегия' },
    { id: 'filter-country-22', label: 'Monaco', value: 'Монако' },
    { id: 'filter-country-23', label: 'Australia', value: 'Австралия' },
    { id: 'filter-country-24', label: 'Ireland', value: 'Ирландия' },
    { id: 'filter-country-25', label: 'Netherlands', value: 'Нидерланды' },
    { id: 'filter-country-26', label: 'Canada', value: 'Канада' },
    { id: 'filter-country-27', label: 'Czech Republic', value: 'Чехия' },
    { id: 'filter-country-28', label: 'Hong Kong', value: 'Гонконг' },
    { id: 'filter-country-29', label: 'United Kingdom', value: 'Великобритания' },
    { id: 'filter-country-30', label: 'Chile', value: 'Чили' },
  ] satisfies SelectOption[],
};
